# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.insert_bit as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = 0.001
    module_0.insert_mult_bits(float_0, float_0, float_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.insert_one_bit(none_type_0, none_type_0, none_type_0)
