# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.tree.bst.array_to_bst as module_0


def test_case_0():
    str_0 = "r\\0h:\x0b5C\tXo:\x0clvB~\\<w"
    var_0 = module_0.array_to_bst(str_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "algorithms.tree.bst.array_to_bst.TreeNode"
    )
    assert var_0.val == "o"
    assert (
        f"{type(var_0.left).__module__}.{type(var_0.left).__qualname__}"
        == "algorithms.tree.bst.array_to_bst.TreeNode"
    )
    assert (
        f"{type(var_0.right).__module__}.{type(var_0.right).__qualname__}"
        == "algorithms.tree.bst.array_to_bst.TreeNode"
    )
