# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.find_difference as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = 377.4
    str_0 = ""
    var_0 = module_0.find_difference(str_0, str_0)
    assert var_0 == "\x00"
    object_0 = module_1.object()
    list_0 = [float_0, var_0, float_0, object_0]
    module_0.find_difference(list_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.find_difference(none_type_0, none_type_0)
