# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.bit.binary_gap as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.binary_gap_improved(bool_0)
    assert var_0 == 0
    var_1 = module_0.binary_gap_improved(bool_0)
    assert var_1 == 0


def test_case_1():
    bool_0 = False
    var_0 = module_0.binary_gap(bool_0)
    assert var_0 == 0
    var_1 = module_0.binary_gap_improved(bool_0)
    assert var_1 == 0
    var_2 = module_0.binary_gap(var_1)
    assert var_2 == 0
    var_3 = module_0.binary_gap(var_2)
    assert var_3 == 0
    var_4 = module_0.binary_gap(var_3)
    assert var_4 == 0
    var_5 = module_0.binary_gap(var_1)
    assert var_5 == 0
    var_6 = module_0.binary_gap(var_5)
    assert var_6 == 0
    var_7 = module_0.binary_gap_improved(var_2)
    assert var_7 == 0
    var_8 = module_0.binary_gap(var_5)
    assert var_8 == 0
