# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.word_squares as module_0
import collections.abc as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    dict_0 = {}
    list_0 = [dict_0, dict_0]
    module_0.word_squares(list_0)


def test_case_1():
    str_0 = "U?-?WT2/"
    list_0 = [str_0, str_0]
    var_0 = module_0.word_squares(list_0)
    var_1 = module_0.word_squares(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = 4721.09
    module_0.word_squares(float_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "??T2/"
    var_0 = module_1.ValuesView(str_0)
    list_0 = [str_0, str_0]
    var_1 = module_0.word_squares(list_0)
    var_2 = module_0.word_squares(list_0)
    module_0.word_squares(var_1)
