# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.single_number3 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 3736
    list_0 = [int_0, int_0, int_0]
    var_0 = module_0.single_number3(list_0)
    int_1 = 2696
    module_0.single_number3(int_1)


def test_case_1():
    list_0 = []
    var_0 = module_0.single_number3(list_0)


def test_case_2():
    bytes_0 = b"\x9a4\x89v\xbf\xb2=\xee\xcfo\xd5@\x1f\xda\xf7"
    var_0 = module_0.single_number3(bytes_0)
    var_1 = module_0.single_number3(var_0)
    var_2 = module_0.single_number3(var_0)
    var_3 = module_0.single_number3(var_0)
    var_4 = module_0.single_number3(var_3)
    var_5 = module_0.single_number3(var_4)
