# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.roman_to_int as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "!V"
    module_0.roman_to_int(str_0)


def test_case_1():
    str_0 = "V"
    int_0 = module_0.roman_to_int(str_0)
    assert int_0 == 5


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "LMfykeAM+$YHc\x0cf]P_G"
    module_0.roman_to_int(str_0)


def test_case_3():
    str_0 = "III"
    int_0 = module_0.roman_to_int(str_0)
    assert int_0 == 3
