# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.linkedlist.is_palindrome as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    var_0 = module_0.is_palindrome(none_type_0)
    assert var_0 is True
    module_0.is_palindrome(var_0)


def test_case_1():
    bool_0 = False
    var_0 = module_0.is_palindrome(bool_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_2():
    tuple_0 = ()
    var_0 = module_0.is_palindrome_stack(tuple_0)
    assert var_0 is True
    module_0.is_palindrome_stack(var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"PA"
    module_0.is_palindrome_dict(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    var_0 = module_0.is_palindrome_dict(none_type_0)
    assert var_0 is True
    module_0.is_palindrome_dict(var_0)
