# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.add_bitwise_operator as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -1348
    list_0 = [int_0, int_0, int_0, int_0]
    module_0.add_bitwise_operator(list_0, list_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.add_bitwise_operator(none_type_0, none_type_0)
    bool_0 = False
    var_1 = module_0.add_bitwise_operator(var_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 2687
    var_0 = module_0.add_bitwise_operator(int_0, int_0)
    assert var_0 == 5374
    list_0 = [int_0]
    module_0.add_bitwise_operator(list_0, list_0)
