# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.strings.int_to_roman as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.int_to_roman(bool_0)
    assert var_0 == "I"
