# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.license_number as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "p9r=`f{u,B)Do^`U\x0c85"
    none_type_0 = None
    module_0.license_number(str_0, none_type_0)


def test_case_1():
    str_0 = "0*"
    bool_0 = True
    var_0 = module_0.license_number(str_0, bool_0)
    assert var_0 == "0-*"


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "0*"
    bool_0 = True
    var_0 = module_0.license_number(str_0, bool_0)
    assert var_0 == "0-*"
    module_0.license_number(var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 2354
    set_0 = {int_0}
    module_0.license_number(set_0, int_0)
