# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dfs.all_factors as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 2553
    var_0 = module_0.get_factors(int_0)
    var_1 = module_0.get_factors(int_0)
    var_2 = module_0.get_factors_iterative2(int_0)
    module_0.get_factors_iterative1(var_2)


def test_case_1():
    int_0 = -1634
    var_0 = module_0.get_factors(int_0)
    var_1 = module_0.get_factors_iterative2(int_0)
    var_2 = module_0.get_factors_iterative1(int_0)


def test_case_2():
    bool_0 = False
    var_0 = module_0.get_factors_iterative1(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.get_factors(none_type_0)


def test_case_4():
    int_0 = 3380
    var_0 = module_0.get_factors_iterative1(int_0)
