# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.subsets as module_0


def test_case_0():
    set_0 = set()
    var_0 = module_0.subsets(set_0)
    var_1 = module_0.subsets(set_0)
    var_2 = module_0.subsets_v2(var_1)
    tuple_0 = ()
    var_3 = module_0.subsets_v2(tuple_0)
    var_4 = module_0.subsets_v2(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 21
    list_0 = [int_0]
    var_0 = module_0.subsets_v2(list_0)
    str_0 = '"\r|SBhj\x0bmx-CgUenH{'
    var_1 = module_0.subsets(str_0)
    none_type_0 = None
    module_0.subsets(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -1002
    module_0.subsets_v2(int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.subsets(none_type_0)
