# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.longest_consecutive as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    var_0 = module_0.dfs(none_type_0, none_type_0, none_type_0, none_type_0)
    var_1 = module_0.longest_consecutive(var_0)
    assert var_1 == 0
    module_0.dfs(var_1, var_1, var_1, var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "E;[U(d(k5z%6J!T\nt"
    list_0 = [str_0, str_0, str_0]
    module_0.longest_consecutive(list_0)


def test_case_2():
    complex_0 = 347.38 + 1791.4j
    none_type_0 = None
    var_0 = module_0.dfs(none_type_0, none_type_0, complex_0, none_type_0)
    var_1 = module_0.dfs(none_type_0, none_type_0, complex_0, complex_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    module_0.dfs(bool_0, bool_0, bool_0, bool_0)
