# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.knuth_morris_pratt as module_0


def test_case_0():
    str_0 = "!!O"
    list_0 = module_0.knuth_morris_pratt(str_0, str_0)


def test_case_1():
    str_0 = "F"
    list_0 = module_0.knuth_morris_pratt(str_0, str_0)


def test_case_2():
    str_0 = "!!O"
    list_0 = module_0.knuth_morris_pratt(str_0, str_0)
    list_1 = module_0.knuth_morris_pratt(list_0, str_0)


def test_case_3():
    int_0 = 165
    list_0 = [int_0, int_0, int_0]
    list_1 = module_0.knuth_morris_pratt(list_0, list_0)


def test_case_4():
    int_0 = 26
    set_0 = set()
    tuple_0 = (int_0, int_0, int_0, set_0)
    list_0 = module_0.knuth_morris_pratt(set_0, tuple_0)


def test_case_5():
    str_0 = "\n        Args:\n            node1, node2 (int): Indexes of nodes whose sets will be merged.\n        "
    str_1 = "(lT5D4v{"
    list_0 = module_0.knuth_morris_pratt(str_0, str_1)


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = "        Args:\n           node1, node (int): Indexes of nodes whose sets will be merged.\n        "
    list_0 = module_0.knuth_morris_pratt(str_0, str_0)
    bool_0 = True
    module_0.knuth_morris_pratt(str_0, bool_0)


def test_case_7():
    str_0 = "\n        Args:\n            node1, node2 (int): Indexes of nodes whose sets will be merged.\n        "
    list_0 = module_0.knuth_morris_pratt(str_0, str_0)
    str_1 = "\n        Args:\nc y         node1, node2 (int): Indexes of nodes whose sets will be merged.\n        "
    list_1 = module_0.knuth_morris_pratt(str_1, str_0)


def test_case_8():
    str_0 = "\n        Args:\n           node1, node2 (int): Indees of nodes whose sets will be merged.\n  3 '   "
    list_0 = module_0.knuth_morris_pratt(str_0, str_0)
    str_1 = "\n        Args:\nc y         node1, node2 (int): Indexes of nodes whose sets will be merged.\n        "
    list_1 = module_0.knuth_morris_pratt(str_1, str_0)
    list_2 = module_0.knuth_morris_pratt(str_0, str_1)
