# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.single_number2 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    module_0.single_number2(list_0)


def test_case_1():
    dict_0 = {}
    var_0 = module_0.single_number2(dict_0)
    assert var_0 == 0
    var_1 = module_0.single_number2(dict_0)
    assert var_1 == 0
    var_2 = module_0.single_number2(dict_0)
    assert var_2 == 0
    var_3 = module_0.single_number2(dict_0)
    assert var_3 == 0


@pytest.mark.xfail(strict=True)
def test_case_2():
    object_0 = module_1.object()
    module_0.single_number2(object_0)
