# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.make_sentence as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    dict_0 = {}
    none_type_0 = None
    var_0 = module_0.make_sentence(dict_0, none_type_0)
    bytes_0 = b"j\xe7\xbb"
    var_1 = module_0.make_sentence(bytes_0, bytes_0)
    assert var_1 is True
    module_0.make_sentence(var_1, var_1)


def test_case_1():
    bytes_0 = b"j\xe7\xbb"
    var_0 = module_0.make_sentence(bytes_0, bytes_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.make_sentence(bool_0, bool_0)


def test_case_3():
    str_0 = "K"
    str_1 = "K2xr4jm\\iN"
    tuple_0 = (str_0, str_0, str_0, str_0)
    var_0 = module_0.make_sentence(str_1, tuple_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "0"
    var_0 = module_0.make_sentence(str_0, str_0)
    assert var_0 is True
    str_1 = "u+U^uasN\r_RT?s5"
    module_0.make_sentence(str_1, str_0)
