# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.bit.flip_bit_longest_sequence as module_0


def test_case_0():
    int_0 = 166
    var_0 = module_0.flip_bit_longest_seq(int_0)
    assert var_0 == 3


def test_case_1():
    bool_0 = True
    none_type_0 = None
    var_0 = module_0.flip_bit_longest_seq(none_type_0)
    assert var_0 == 1
    var_1 = module_0.flip_bit_longest_seq(bool_0)
    assert var_1 == 2
