# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.bit.remove_bit as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.remove_bit(bool_0, bool_0)
    assert var_0 == 1
    bool_1 = False
    var_1 = module_0.remove_bit(var_0, bool_1)
    assert var_1 == 0
    var_2 = module_0.remove_bit(bool_1, bool_1)
