# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.fizzbuzz as module_0


def test_case_0():
    float_0 = -2823.738553
    with pytest.raises(ValueError):
        module_0.fizzbuzz(float_0)


def test_case_1():
    bool_0 = True
    var_0 = module_0.fizzbuzz(bool_0)


def test_case_2():
    bool_0 = True
    var_0 = module_0.fizzbuzz(bool_0)
    var_1 = module_0.fizzbuzz_with_helper_func(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    var_0 = module_0.fizzbuzz(bool_0)
    bytes_0 = b'\xe8B\xa7="]~g'
    int_0 = 1993
    var_1 = module_0.fizzbuzz_with_helper_func(int_0)
    module_0.fb(bytes_0)


def test_case_4():
    none_type_0 = None
    with pytest.raises(TypeError):
        module_0.fizzbuzz(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    none_type_0 = None
    module_0.fizzbuzz_with_helper_func(none_type_0)


def test_case_6():
    int_0 = 1993
    var_0 = module_0.fizzbuzz(int_0)
