# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.single_number as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "Z"
    list_0 = [str_0, str_0, str_0]
    module_0.single_number(list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    dict_0 = {}
    var_0 = module_0.single_number(dict_0)
    assert var_0 == 0
    var_1 = module_0.single_number(dict_0)
    assert var_1 == 0
    tuple_0 = ()
    var_2 = module_0.single_number(tuple_0)
    assert var_2 == 0
    object_0 = module_1.object(**dict_0)
    module_0.single_number(object_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.single_number(none_type_0)
