# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.atbash_cipher as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"x\xafX\x02\xec"
    module_0.atbash(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "wqQ5k`BR<x}ZK%6s"
    var_0 = module_0.atbash(str_0)
    assert var_0 == "djJ5p`YI<c}AP%6h"
    bool_0 = False
    module_0.atbash(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.atbash(bool_0)
