# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.is_subtree as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.is_subtree(none_type_0, none_type_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.comp(none_type_0, none_type_0)
    assert var_0 is True


def test_case_2():
    float_0 = 962.0
    none_type_0 = None
    var_0 = module_0.comp(float_0, none_type_0)
    assert var_0 is False


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"\x19\xe44\x82c\xc1"
    none_type_0 = None
    var_0 = module_0.comp(bytes_0, none_type_0)
    assert var_0 is False
    var_1 = module_0.comp(none_type_0, var_0)
    assert var_1 is False
    module_0.comp(var_1, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bytes_0 = b"\x05\x8b'4\xc2\xba(\xb8`\xe3\xcc\xed\xd5oWt"
    module_0.comp(bytes_0, bytes_0)
