# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.swap_pair as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xc7u\xd6\xa2\x91\xf5^Q\xf1\xdc@W1ir6\xa9.\xd1"
    module_0.swap_pair(bytes_0)
