# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.strong_password as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    set_0 = set()
    module_0.strong_password(set_0, set_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "-u1\x0c"
    none_type_0 = None
    module_0.strong_password(none_type_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = (
        "\n        Get a string representation of\n        the polynomial.\n        "
    )
    module_0.strong_password(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.strong_password(none_type_0, none_type_0)
