# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.is_symmetric as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.is_symmetric(none_type_0)
    assert var_0 is True
    var_1 = module_0.helper(none_type_0, var_0)
    assert var_1 is False


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    dict_0 = {bool_0: bool_0}
    module_0.is_symmetric(dict_0)


def test_case_2():
    none_type_0 = None
    var_0 = module_0.helper(none_type_0, none_type_0)
    assert var_0 is True
    var_1 = module_0.is_symmetric_iterative(none_type_0)
    assert var_1 is True


def test_case_3():
    bytes_0 = b"E\xb0i\x99\x1et\x93\x02"
    var_0 = module_0.helper(bytes_0, bytes_0)
    assert var_0 is False


@pytest.mark.xfail(strict=True)
def test_case_4():
    bytes_0 = b"\t[J"
    module_0.is_symmetric_iterative(bytes_0)


def test_case_5():
    none_type_0 = None
    str_0 = "_v"
    var_0 = module_0.helper(none_type_0, str_0)
    assert var_0 is False
