# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.bfs.count_islands as module_0


def test_case_0():
    bytes_0 = b"\xb6\x01\xac]\\\x00AU\xe6_G"
    list_0 = [bytes_0, bytes_0]
    var_0 = module_0.count_islands(list_0)
    assert var_0 == 1


def test_case_1():
    bytes_0 = b"\x01]\\\x00U\xc1\xe6_G"
    list_0 = [bytes_0, bytes_0, bytes_0, bytes_0]
    var_0 = module_0.count_islands(list_0)
    assert var_0 == 1


def test_case_2():
    bytes_0 = b"\x01"
    list_0 = [bytes_0, bytes_0, bytes_0, bytes_0, bytes_0, bytes_0]
    var_0 = module_0.count_islands(list_0)
    assert var_0 == 1
