# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.judge_circle as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xa8\xdbu=*@\x1edDW-p\x82\xd4\xe45"
    module_0.judge_circle(bytes_0)


def test_case_1():
    dict_0 = {}
    var_0 = module_0.judge_circle(dict_0)
    assert var_0 is True


def test_case_2():
    str_0 = "R"
    var_0 = module_0.judge_circle(str_0)
    assert var_0 is False
