# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.traversal.zigzag as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = -2885.0
    module_0.zigzag_level(float_0)


def test_case_1():
    none_type_0 = None
    list_0 = module_0.zigzag_level(none_type_0)


def test_case_2():
    none_type_0 = None
    node_0 = module_0.Node(none_type_0, none_type_0)
    list_0 = module_0.zigzag_level(node_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    node_0 = module_0.Node(bool_0, right=bool_0)
    module_0.zigzag_level(node_0)


def test_case_4():
    str_0 = "FI=tnZh,%hS&%\t%*_"
    list_0 = [str_0, str_0, str_0, str_0]
    int_0 = -1493
    node_0 = module_0.Node(int_0)
    list_1 = module_0.zigzag_level(node_0)
    node_1 = module_0.Node(int_0)
    none_type_0 = None
    node_2 = module_0.Node(none_type_0, node_1)
    list_2 = module_0.zigzag_level(node_1)
    node_3 = module_0.Node(list_0)
    list_3 = module_0.zigzag_level(none_type_0)
    node_4 = module_0.Node(list_2, node_2)
    assert node_4.val == [[-1493]]
    list_4 = module_0.zigzag_level(node_4)
