# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.find_missing_number as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "saTX@J[0S"
    tuple_0 = (str_0,)
    module_0.find_missing_number(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    var_0 = module_0.find_missing_number2(list_0)
    var_1 = module_0.find_missing_number(list_0)
    assert var_1 == 0
    var_2 = module_0.find_missing_number2(list_0)
    var_3 = module_0.find_missing_number2(list_0)
    var_4 = module_0.find_missing_number(list_0)
    assert var_4 == 0
    var_5 = module_0.find_missing_number2(list_0)
    module_0.find_missing_number2(var_4)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.find_missing_number2(none_type_0)
