# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.strings.multiply_strings as module_0


def test_case_0():
    str_0 = "<3 u"
    str_1 = module_0.multiply(str_0, str_0)
    assert str_1 == "149059681"
