# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.bst.is_bst as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xde\t\xef\xbbe4\xc8^"
    module_0.is_bst(bytes_0)


def test_case_1():
    tuple_0 = ()
    var_0 = module_0.is_bst(tuple_0)
    assert var_0 is True
