# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings.repeat_string as module_0
import builtins as module_1


def test_case_0():
    str_0 = "z @&!Lqdms};X|v7"
    str_1 = ";_"
    var_0 = module_0.repeat_string(str_0, str_1)
    assert var_0 == -1


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"U\xdd<@]\xca\xf2/\x03\xbb\xb6xv\xf7_^#\x7f\xb5"
    var_0 = module_0.repeat_string(bytes_0, bytes_0)
    assert var_0 == 1
    module_1.object(**var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    module_0.repeat_string(set_0, set_0)
