# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.traversal.level_order as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    module_0.level_order(bool_0)


def test_case_1():
    none_type_0 = None
    list_0 = module_0.level_order(none_type_0)


def test_case_2():
    int_0 = -1753
    node_0 = module_0.Node(int_0, right=int_0)


def test_case_3():
    int_0 = 399
    node_0 = module_0.Node(int_0)
    list_0 = module_0.level_order(node_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = -1753
    node_0 = module_0.Node(int_0, right=int_0)
    module_0.level_order(node_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 255
    node_0 = module_0.Node(int_0)
    list_0 = module_0.level_order(node_0)
    int_1 = -1157
    node_1 = module_0.Node(int_1)
    node_2 = module_0.Node(int_0, node_1)
    list_1 = module_0.level_order(node_2)
    int_2 = 2370
    module_0.level_order(int_2)
