# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.bit.bit_operation as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x88w\x88\xb0y(kE\xcaM\xe7\xb1"
    module_0.set_bit(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -815
    dict_0 = {int_0: int_0, int_0: int_0}
    list_0 = [int_0, dict_0]
    none_type_0 = None
    module_0.get_bit(list_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"M("
    module_0.clear_bit(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.update_bit(none_type_0, none_type_0, none_type_0)
