# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.tree.bst.predecessor as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    var_0 = module_0.predecessor(bool_0, bool_0)
    int_0 = -3473
    module_0.predecessor(int_0, int_0)
